### ISSUE TITLE
Randomness Issue with Firefox

### ISSUE THREAD

**Issue by EdwardJFox** [snapish/Multiman#36]
I've been noticing recurring randomisation issues with the site in Firefox. It seems to always heavily bias towards the initial starting positions of the characters. I believe this is an issue with the `.sort` method of randomisation used with the site.

Heres an image showing an example off Firefox. You'll note that across all the players the characters are roughly in the same positions they are in the CSS, and on hitting the randomise button you'll get similar results.
![random](https://user-images.githubusercontent.com/6260917/122649762-639b8b80-d127-11eb-9276-b007a20f3cf6.PNG)

Environment:
- Windows 10
- Firefox 89.0.1
- AMD 3900x (not sure thats relevant)

Also tested this on a MacBook Pro with Firefox and noticed the exact same issue, but I am unable to provide any data off of that device. This does not seem to be an issue with Chrome or Safari on any of my devices (PC, MacBook, iPad).

**Comment by snapish** [comment]
Yo this is big, thanks man. I'm not sure if you were in the discord, but I
had other people just reporting the same issues. I'm currently traveling
and can't really dig into it right now, but once I get a chance I'll try
get it fixed as fast as I can. I'd never know about this if ppl like you
didn't report issues, so I super appreciate it.
